"""add openclaw chat persistence tables

Revision ID: e6ddef2e455e
Revises: c0d41fb70671
Create Date: 2026-04-18 14:03:21.729256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6ddef2e455e'
down_revision: Union[str, Sequence[str], None] = 'c0d41fb70671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openclawconversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openclawconversation_agent_id'), 'openclawconversation', ['agent_id'], unique=False)
    op.create_index(op.f('ix_openclawconversation_user_id'), 'openclawconversation', ['user_id'], unique=False)
    op.create_table('openclawmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachments_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['openclawconversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openclawmessage_conversation_id'), 'openclawmessage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_openclawmessage_role'), 'openclawmessage', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_openclawmessage_role'), table_name='openclawmessage')
    op.drop_index(op.f('ix_openclawmessage_conversation_id'), table_name='openclawmessage')
    op.drop_table('openclawmessage')
    op.drop_index(op.f('ix_openclawconversation_user_id'), table_name='openclawconversation')
    op.drop_index(op.f('ix_openclawconversation_agent_id'), table_name='openclawconversation')
    op.drop_table('openclawconversation')
    # ### end Alembic commands ###
